
@echo off

echo Command: install
if "install" == "" ( exit )

echo Command: %2
if "%2" == "" ( exit )

c:\Code\bin\code --install-extension alefragnani.rtf --force --install-extension anseki.vscode-color --force --install-extension beaugust.blamer-vs --force --install-extension bmewburn.vscode-intelephense-client --force --install-extension brunnerh.file-properties-viewer --force --install-extension christian-kohler.npm-intellisense --force --install-extension davidanson.vscode-markdownlint --force --install-extension yzhang.markdown-all-in-one --force --install-extension dbaeumer.vscode-eslint --force --install-extension donjayamanne.githistory --force --install-extension dotjoshjohnson.xml --force --install-extension eamodio.gitlens --force --install-extension esbenp.prettier-vscode --install-extension eg2.vscode-npm-script --force --install-extension fabiospampinato.vscode-todo-plus --force --install-extension hookyqr.beautify --force --install-extension github.vscode-pull-request-github --force --install-extension humao.rest-client --force --install-extension ibm.output-colorizer --force --install-extension idleberg.nsis --force --install-extension idleberg.nsl-assembler --force --install-extension idleberg.bridlensis --force --install-extension johnstoncode.svn-scm --force --install-extension momoto.binary-viewer --force --install-extension ms-python.python --force --install-extension ms-vscode.azure-account --force --install-extension ms-azure-devops.azure-pipelines --force --install-extension ms-azuretools.vscode-azureappservice --force --install-extension ms-azuretools.vscode-azurestorage --force --install-extension ms-mssql.mssql --force --install-extension ms-vscode.cpptools --force --install-extension ms-dotnettools.csharp --force --install-extension ms-vscode.powershell --force --install-extension ms-vscode-remote.remote-ssh --force --install-extension ms-vscode.vscode-typescript-tslint-plugin --force --install-extension msjsdiag.debugger-for-chrome --force --install-extension msjsdiag.debugger-for-edge --force --install-extension nobuhito.printcode --force --install-extension pdconsec.vscode-print --force --install-extension pkief.material-icon-theme --force --install-extension ruakr.ftp-kr --force --install-extension techer.open-in-browser --force --install-extension oracle.oracledevtools --force --install-extension redhat.java --force --install-extension sandcastle.vscode-open --force --install-extension softwaredotcom.swdc-vscode --force --install-extension spmeesseman.svn-scm-ext --force --install-extension spmeesseman.vscode-taskexplorer --force --install-extension spmeesseman.vscode-vslauncher --force --install-extension tht13.html-preview-vscode --force --install-extension tomoki1207.pdf --force --install-extension visualstudioexptteam.vscodeintellicode --force --install-extension tomoki1207.vscode-pdf --force --install-extension vscjava.vscode-java-pack --force --install-extension xyz.plsql-language --force --install-extension yzane.markdown-pdf --force --install-extension yzhang.markdown-all-in-one --force 
