
@echo off

echo Command: %1
if "%1" == "" ( exit )

echo Command: %2
if "%2" == "" ( exit )

"%~pd0\bin\%2" %1 alefragnani.rtf --force %1 anseki.vscode-color --force %1 beaugust.blamer-vs --force %1 bmewburn.vscode-intelephense-client --force %1 brunnerh.file-properties-viewer --force %1 christian-kohler.npm-intellisense --force %1 davidanson.vscode-markdownlint --force %1 yzhang.markdown-all-in-one --force %1 dbaeumer.vscode-eslint --force %1 donjayamanne.githistory --force %1 dotjoshjohnson.xml --force %1 eamodio.gitlens --force %1 esbenp.prettier-vscode %1 eg2.vscode-npm-script --force %1 fabiospampinato.vscode-todo-plus --force %1 hookyqr.beautify --force %1 github.vscode-pull-request-github --force %1 humao.rest-client --force %1 ibm.output-colorizer --force %1 idleberg.nsis --force %1 idleberg.nsl-assembler --force %1 idleberg.bridlensis --force %1 johnstoncode.svn-scm --force %1 momoto.binary-viewer --force %1 ms-python.python --force %1 ms-vscode.azure-account --force %1 ms-azure-devops.azure-pipelines --force %1 ms-azuretools.vscode-azureappservice --force %1 ms-azuretools.vscode-azurestorage --force %1 ms-mssql.mssql --force %1 ms-vscode.cpptools --force %1 ms-dotnettools.csharp --force %1 ms-vscode.powershell --force %1 ms-vscode-remote.remote-ssh --force %1 ms-vscode.vscode-typescript-tslint-plugin --force %1 msjsdiag.debugger-for-chrome --force %1 msjsdiag.debugger-for-edge --force %1 nobuhito.printcode --force %1 pdconsec.vscode-print --force %1 pkief.material-icon-theme --force %1 ruakr.ftp-kr --force %1 techer.open-in-browser --force %1 oracle.oracledevtools --force %1 redhat.java --force %1 sandcastle.vscode-open --force %1 softwaredotcom.swdc-vscode --force %1 spmeesseman.svn-scm-ext --force %1 spmeesseman.vscode-taskexplorer --force %1 spmeesseman.vscode-vslauncher --force %1 tht13.html-preview-vscode --force %1 tomoki1207.pdf --force %1 visualstudioexptteam.vscodeintellicode --force %1 tomoki1207.vscode-pdf --force %1 vscjava.vscode-java-pack --force %1 xyz.plsql-language --force %1 yzane.markdown-pdf --force %1 yzhang.markdown-all-in-one --force 
